### ISSUE TITLE
大佬，求解决:magic number is not correct

### ISSUE THREAD

**Issue by highskyno1** [museL/wxappUnpacker-master#13]
E:\微信小程序逆向\wxappUnpacker-master-master>node wuWxapkg.js C:\123.wxapkg
Unpack file C:\123.wxapkg...

Header info:
  firstMark: 0x56
  unknownInfo:  827149655
  infoListLength:  1491230453
  dataLength:  3851326218
  lastMark: 0x52
E:\微信小程序逆向\wxappUnpacker-master-master\wuWxapkg.js:20
        if(firstMark!=0xbe||lastMark!=0xed)throw Error("Magic number is not corr
ect!");
                                           ^

Error: Magic number is not correct!
    at header (E:\微信小程序逆向\wxappUnpacker-master-master\wuWxapkg.js:20:43)
    at E:\微信小程序逆向\wxappUnpacker-master-master\wuWxapkg.js:111:35
    at E:\微信小程序逆向\wxappUnpacker-master-master\wuLib.js:80:8
    at agent (E:\微信小程序逆向\wxappUnpacker-master-master\wuLib.js:54:14)
[90m    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_f
ile_context.js:61:3)[39m

E:\微信小程序逆向\wxappUnpacker-master-master>

**Comment by highskyno1** [comment]
这是我逆向的文件。
[123.zip](https://github.com/museL/wxappUnpacker-master/files/4051882/123.zip)

**Comment by zongshuai** [comment]
我也是，请求解决了吗

**Comment by bloginn** [comment]
请问解决了吗

**Comment by helloprogram6** [comment]
.wxapkg文件不对吧？在安卓模拟器上登录微信，获取模拟器上的 .wxapkg文件

**Comment by SwpuEsine** [comment]
我用的windows打开的apkg包可以吗.就是windows现在也可以打开小程序的

**Comment by dengshilong** [comment]
电脑端的wxapkg得先用UnpackMiniApp解密工具解密下
