### ISSUE TITLE
wxss还是出不来啊

### ISSUE THREAD

**Issue by jihuoxia** [museL/wxappUnpacker-master#2]
执行node wuWxss.js 命令出不来wxss文件
js和wxml倒是能出来，啥情况

**Comment by museL** [comment]
报什么错，或者你发我看看

**Comment by jihuoxia** [comment]
报错

C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2>node wuWxss.js C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2\2\3\longbing_card\users\pages
C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2\wuWxss.js:313
else throw Error("page-frame-like file is not found in the package by auto.");
     ^

Error: page-frame-like file is not found in the package by auto.
    at Array.wu.scanDirByExt.files (C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2\wuWxss.js:313:12)
    at CntEvent.decount (C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2\wuLib.js:17:43)
    at fs.stat (C:\Users\xiari\AppData\Roaming\npm\node_modules\wxappUnpacker2\wuLib.js:104:16)
    at FSReqWrap.oncomplete (fs.js:155:5)

**Comment by jihuoxia** [comment]
> 报什么错，或者你发我看看

大神给看看咋回事

**Comment by museL** [comment]
你这个是哪个小程序，感觉抓错包了

**Comment by jihuoxia** [comment]
> 你这个是哪个小程序，感觉抓错包了

没有错，这个名片的 小程序5个分包，这是其中一个分包

**Comment by museL** [comment]
小程序名叫啥，我自己去抓看看

**Comment by jihuoxia** [comment]
> 小程序名叫啥，我自己去抓看看

龙兵名片，你抓的话 抓不全分包啊，雷达模块只能是你搭建的小程序 才能在你手机显示

**Comment by jihuoxia** [comment]
> > 小程序名叫啥，我自己去抓看看
> 
> 龙兵名片，你抓的话 抓不全分包啊，雷达模块只能是你搭建的小程序 才能在你手机显示

分包不全也没关系，你看看抓下来的分包能不能解出wxss
